In [15]:
# Dependencies
import pandas as pd

In [16]:
# Load Files
acad_outcomes_data_to_load = "acad_outcomes.csv"
growth_data_to_load = "GroupByDistrictNameGrowth.csv"

In [21]:
# Read School and Student Data File and store into Pandas Data Frames
acad_outcomes_data = pd.read_csv(acad_outcomes_data_to_load, delimiter=',', encoding="utf-8-sig", dtype={'ACT Percent': int})
#acad_outcomes_data = pd.read_csv(acad_outcomes_data_to_load)
student_growth_data = pd.read_csv(growth_data_to_load)

In [22]:
student_growth_data.head()

,District_Name,School_Code,School Name,Subgroup,School Growth Status,School Growth Index Score
0,Alamance-Burlington Schools,10303,ABSS Early College at ACC,Academically or Intellectually Gifted,Met,-1.09
1,Alamance-Burlington Schools,10303,ABSS Early College at ACC,All Students,Met,0.15
2,Alamance-Burlington Schools,10303,ABSS Early College at ACC,Black,Met,0.79
3,Alamance-Burlington Schools,10303,ABSS Early College at ACC,Economically Disadvantaged,Met,0.68
4,Alamance-Burlington Schools,10303,ABSS Early College at ACC,Hispanic,Met,0.05

In [23]:
LEA_student_growth_data = pd.DataFrame(student_growth_data.groupby(['District_Name', 'Subgroup']).mean()['School Growth Index Score'])
LEA_student_growth_data.head()

                                                                   School Growth Index Score
District_Name               Subgroup
Alamance-Burlington Schools Academically or Intellectually Gifted                   0.717143
                            All Students                                            0.050000
                            Black                                                  -0.021429
                            Economically Disadvantaged                             -0.395714
                            English Learner                                        -0.008000

In [24]:
table_LEA_student_growth_data = LEA_student_growth_data.unstack(level = -1)
table_LEA_student_growth_data.columns = table_LEA_student_growth_data.columns.get_level_values(1)
table_LEA_student_growth_data.head()

Subgroup,Academically or Intellectually Gifted,All Students,American Indian,Asian,Black,Economically Disadvantaged,English Learner,Hispanic,Students With Disabilities,Two or More Races,White
District_Name,,,,,,,,,,,
Alamance-Burlington Schools,0.717143,0.05,NaN,NaN,-0.021429,-0.395714,-0.008,0.998571,-1.013333,-0.048333,-0.758571
Alexander County Schools,1.940000,-1.51,NaN,NaN,-0.750000,-2.450000,NaN,-0.960000,-0.400000,-0.040000,-1.270000
Alleghany County Schools,-1.130000,-1.96,NaN,NaN,NaN,-1.040000,NaN,-0.030000,-2.020000,NaN,-2.270000
Anson County Schools,-1.885000,-2.04,NaN,NaN,-1.540000,-1.523333,NaN,-1.340000,-1.900000,NaN,-1.855000
Ashe County Schools,-3.590000,-9.07,NaN,NaN,NaN,-7.990000,-0.680,-2.010000,-5.310000,NaN,-9.370000

In [25]:
# Renames columns to be more readable
table_LEA_student_growth_data = table_LEA_student_growth_data.rename(columns={"Academically or Intellectually Gifted":"Growth_AIG",
                                           "All Sttudents":"Growth_All", 
                                           "American Indian": "Growth_American Indian",
                                           "Asian": "Growth_Asian", 
                                           "Black": "Growth_Black",
                                           "Economically Disadvantaged": "Growth_ED",
                                        "English Learner": "Growth_ELL",
                                           "Hispanic": "Growth_Hispanic",
                                           "Students With Disabilities": "Growth_SwD",
                                           "Two or More Races": "Growth_MultiRacial",
                                        "White": "Growth_White"})
# Iterates through all column data to find NaN values and adds them to a list
table_LEA_student_growth_data.columns[table_LEA_student_growth_data.isna().any()].tolist()
table_LEA_student_growth_data.head()

Subgroup,Growth_AIG,All Students,Growth_American Indian,Growth_Asian,Growth_Black,Growth_ED,Growth_ELL,Growth_Hispanic,Growth_SwD,Growth_MultiRacial,Growth_White
District_Name,,,,,,,,,,,
Alamance-Burlington Schools,0.717143,0.05,NaN,NaN,-0.021429,-0.395714,-0.008,0.998571,-1.013333,-0.048333,-0.758571
Alexander County Schools,1.940000,-1.51,NaN,NaN,-0.750000,-2.450000,NaN,-0.960000,-0.400000,-0.040000,-1.270000
Alleghany County Schools,-1.130000,-1.96,NaN,NaN,NaN,-1.040000,NaN,-0.030000,-2.020000,NaN,-2.270000
Anson County Schools,-1.885000,-2.04,NaN,NaN,-1.540000,-1.523333,NaN,-1.340000,-1.900000,NaN,-1.855000
Ashe County Schools,-3.590000,-9.07,NaN,NaN,NaN,-7.990000,-0.680,-2.010000,-5.310000,NaN,-9.370000

In [26]:
final_student_growth = table_LEA_student_growth_data.reset_index()
final_student_growth.head()

Subgroup,District_Name,Growth_AIG,All Students,Growth_American Indian,Growth_Asian,Growth_Black,Growth_ED,Growth_ELL,Growth_Hispanic,Growth_SwD,Growth_MultiRacial,Growth_White
0,Alamance-Burlington Schools,0.717143,0.05,NaN,NaN,-0.021429,-0.395714,-0.008,0.998571,-1.013333,-0.048333,-0.758571
1,Alexander County Schools,1.940000,-1.51,NaN,NaN,-0.750000,-2.450000,NaN,-0.960000,-0.400000,-0.040000,-1.270000
2,Alleghany County Schools,-1.130000,-1.96,NaN,NaN,NaN,-1.040000,NaN,-0.030000,-2.020000,NaN,-2.270000
3,Anson County Schools,-1.885000,-2.04,NaN,NaN,-1.540000,-1.523333,NaN,-1.340000,-1.900000,NaN,-1.855000
4,Ashe County Schools,-3.590000,-9.07,NaN,NaN,NaN,-7.990000,-0.680,-2.010000,-5.310000,NaN,-9.370000

In [28]:
# Export file as a CSV, without the Pandas index, but with the header
final_student_growth.to_csv("/Users/erikaberry/Desktop/Web-Design-Challenge/subgroup_growth_byLEA.csv", index=False, header=True)